learning_users/basicapp/urls.py
from django.urls import path
from basicapp import views
from django.conf import settings
from django.conf.urls.static import static
app_name = "basicapp"

urlpatterns = [
    path('register/', views.register, name = 'register'),
    path('user_login/', views.user_login, name = 'user_login'),
    path('special/', views.special, name = 'special'),
 ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path,include
from basicapp import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.index, name = 'index'),
    path("basicapp/", include('basicapp.urls')),
    path("logout/", views.user_logout, name = 'logout'),
    path("special/", views.special, name = 'special'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

learning_users/basicapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.



class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete = models.CASCADE)

    #additional
    portfolio = models.URLField(blank = True)

    profilepic = models.ImageField(upload_to = 'profile_pics', blank = True)


    def __str__(self):
        return self.user.username

learning_users/basicapp/forms.py
from django import forms
from django.contrib.auth.models import User
from basicapp.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        # portfolio = forms.URLField(required = False)
        # profilepic = forms.ImageField(required = False)
        model = UserProfileInfo
        fields = ('portfolio', 'profilepic')

learning_users/basicapp/views.py
from django.shortcuts import render
from basicapp.forms import UserForm,UserProfileInfoForm
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.
def index(request):
    return render(request, 'basicapp/index.html')

@login_required
def special(request):
    return HttpResponse("U r Loged in nice!")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered = False


    if request.method == "POST":

        user_form = UserForm(data = request.POST)
        profile_form = UserProfileInfoForm(data = request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit = False)
            profile.user = user

            if "profilepic" in request.FILES:
                profile.profilepic = request.FILES['profilepic']

            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'basicapp/register.html',{'userform' : user_form,'profileform' : profile_form, 'registered' : registered})

def user_login(request):

    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username = username, password = password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE!")
        else:
            print("Someone tried to login and failed!")
            print(f"Username: {username}, password: {password}")
            return HttpResponse("invalid login details supplied!")
    else:
        return render(request, 'basicapp/login.html',{})

learning_users/templates/basicapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link href="https://fonts.googleapis.com/css2?family=Rowdies:wght@300&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:ital,wght@1,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static "css/css.css" %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top navbar-light " style = "background-color : #34cf5d">
  <a class="navbar-brand" href="{% url 'index' %}">DJANGO</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <!-- <a class="nav-item nav-link active" href="{% url 'admin:index' %}">Admin</a> -->
      <a class="nav-item nav-link active" href="{% url 'basicapp:register' %}">Register</a>
      {% if user.is_authenticated %}
        <a class="nav-item nav-link active" href="{% url 'logout' %}">Logout</a>
        <a class="nav-item nav-link active" href="{% url 'basicapp:special' %}">Special</a>
      {% else %}
        <a class="nav-item nav-link active" href="{% url 'basicapp:user_login' %}">Login</a>
      {% endif %}
    </div>
  </div>
</nav>
<div class="container">
  {% block body_block %}
  {% endblock %}
</div>
  </body>
</html>

learning_users/templates/basicapp/index.html
<!DOCTYPE html>
{% extends './base.html' %}
{% block body_block %}

<div class="jumbotron">
  <h1>Welcom To My Website!</h1>
</div>

{% endblock %}

learning_users/templates/basicapp/login.html
<!DOCTYPE html>
{% extends './base.html' %}
{% block body_block %}

<div class="jumbotron">
  <h1>Please login!</h1>
  <form class="" action="{% url 'basicapp:user_login' %}" method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" palceholder = "Enter Username"><br>
    <label for="password">Password:</label>
    <input type="password" name="password" ><br>
    <input type="submit" name="" value="Login" class="btn btn-outline-success">
  </form>
</div>

{% endblock %}

learning_users/templates/basicapp/register.html
<!DOCTYPE html>
{% extends './base.html' %}
{% load static %}
{% block body_block %}

<div class="jumbotron">
  {% if registered %}
  <h1>Thank You For Registering!</h1>

  {% else %}
    <h1>Register Here!</h1>
    <h3>Fill out the form:</h3>
    <form class="" action="" method="post" enctype="multipart/form-data" >
      {% csrf_token %}
      {{ userform.as_p }}
      {{ profileform.as_p }}
      <input type="submit" class="btn btn-outline-success" name="" value="Register">
    </form>
  {% endif %}

</div>

{% endblock %}